import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/app/lib/supabase-admin";
import { getSession } from "@/app/lib/auth";
import { signedUrl } from "@/app/lib/storage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// GET /api/verkoop/dossier — return the authed seller's dossier + current files.
// Used by portal/index.html to hydrate on ?resume=1, and by the wizard to know
// if intake data was already saved.
export async function GET() {
  const sess = await getSession();
  if (!sess) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const sb = supabaseAdmin();
  const { data: dossier } = await sb
    .from("verkoop_dossiers")
    .select("*")
    .eq("phone_e164", sess.phone_e164)
    .maybeSingle();

  if (!dossier) {
    // No dossier yet, but the seller IS authenticated — surface the
    // session phone so the portal can show "your sign-in number" in the
    // locked chip even before any data has been saved.
    return NextResponse.json({
      ok: true,
      dossier: null,
      files: [],
      seller_phone: sess.phone_e164,
    });
  }

  const { data: files } = await sb
    .from("verkoop_files")
    .select(
      "id, doc_key, filename, mime_type, size_bytes, blob_url, version, uploaded_at, ai_extract_status"
    )
    .eq("dossier_id", dossier.id)
    .eq("is_current", true)
    .order("uploaded_at", { ascending: true });

  // Attach short-lived signed URLs so the seller can preview their own file.
  const filesOut = await Promise.all(
    (files ?? []).map(async (f) => ({
      ...f,
      preview_url: f.blob_url ? await signedUrl(f.blob_url) : null,
    }))
  );

  // Surface AI follow-up questions in the seller's language (generated by
  // the dashboard's analyse endpoint). The portal renders these in step 4
  // alongside the 16 hardcoded questions.
  const followups =
    (dossier as { ai_followup_questions?: { seller_questions?: unknown } | null })
      .ai_followup_questions ?? null;
  const sellerQuestions = Array.isArray(
    (followups as { seller_questions?: unknown[] } | null)?.seller_questions
  )
    ? ((followups as { seller_questions: unknown[] }).seller_questions as Array<{
        id: string;
        question: string;
        if_yes?: string | null;
      }>)
    : [];
  const sellerAnswers =
    (dossier as { ai_followup_answers?: Record<string, unknown> | null })
      .ai_followup_answers ?? null;

  return NextResponse.json({
    ok: true,
    dossier,
    files: filesOut,
    seller_questions: sellerQuestions,
    seller_answers: sellerAnswers,
    seller_phone: sess.phone_e164,
  });
}

// POST /api/verkoop/dossier — upsert step-1 intake into the dossier row.
// Idempotent: keyed on phone_e164. Returns the dossier id.
export async function POST(req: NextRequest) {
  const sess = await getSession();
  if (!sess) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }

  const allowed = [
    "straat",
    "postcode",
    "woonplaats",
    "naam",
    "email",
    "telefoon",
    "taal",
    "vraagprijs",
    "oplev_datum",
    "motivatie",
    "gebreken_toel",
    "vve_sfeer",
    "verbouw_toel",
    "vve_beheerder",
    "vve_email",
    "antwoorden",
    "consent",
  ] as const;

  const patch: Record<string, unknown> = {};
  for (const k of allowed) {
    if (k in body && body[k] !== undefined && body[k] !== null) patch[k] = body[k];
  }
  if (Object.keys(patch).length === 0) {
    return NextResponse.json({ error: "no_fields" }, { status: 400 });
  }

  patch.phone_e164 = sess.phone_e164;
  patch.last_activity_at = new Date().toISOString();
  if (patch.consent === true) patch.consent_at = new Date().toISOString();

  // Required-on-insert defaults for the existing schema's NOT NULL columns.
  // verkoop_dossiers has straat / postcode / naam / email as NOT NULL.
  // For an early upsert (e.g. first save after OTP), seed empty strings —
  // they'll be filled in by subsequent step-1 saves before submit.
  const requiredOnInsert: Record<string, string> = {
    straat: "",
    postcode: "",
    naam: "",
    email: "",
  };

  const sb = supabaseAdmin();
  const { data: existing } = await sb
    .from("verkoop_dossiers")
    .select("id")
    .eq("phone_e164", sess.phone_e164)
    .maybeSingle();

  if (existing) {
    const { data, error } = await sb
      .from("verkoop_dossiers")
      .update(patch)
      .eq("id", existing.id)
      .select("id")
      .single();
    if (error) {
      return NextResponse.json({ error: "db_error", detail: error.message }, { status: 500 });
    }
    return NextResponse.json({ ok: true, id: data.id, created: false });
  }

  const insert = { ...requiredOnInsert, ...patch };
  const { data, error } = await sb
    .from("verkoop_dossiers")
    .insert(insert)
    .select("id")
    .single();
  if (error) {
    return NextResponse.json({ error: "db_error", detail: error.message }, { status: 500 });
  }

  await sb.from("verkoop_audit").insert({
    dossier_id: data.id,
    actor: `seller:${sess.phone_e164}`,
    action: "dossier_created",
    meta: { source: "portal_intake" },
  });

  return NextResponse.json({ ok: true, id: data.id, created: true });
}
