import Anthropic from "@anthropic-ai/sdk";
import { supabaseAdmin } from "./supabase-admin";
import { downloadFile } from "./storage";
import { DOC_DESCRIPTIONS, DOC_KEYS } from "./doc-descriptions";

const MODEL = process.env.VERKOOP_EXTRACT_MODEL || "claude-haiku-4-5";

export type ClassificationResult = {
  doc_key: string;
  confidence: "high" | "medium" | "low";
  reason: string;
};

const CLASSIFICATION_PROMPT = `You are a document classifier for a Dutch apartment-sale platform.
Given a document, determine which of the following document types it is most likely to be.

Document types:
${DOC_KEYS.map((k) => `- ${k}: ${DOC_DESCRIPTIONS[k].en}`).join("\n")}

Respond with JSON only, no prose, no code fences. Schema:
{
  "doc_key": string,
  "confidence": "high" | "medium" | "low",
  "reason": string
}

Rules:
- Pick the single best matching doc_key from the list above.
- Use "high" confidence only if you are very sure.
- Use "medium" if it seems likely but could be something else.
- Use "low" if you are unsure or the document doesn't clearly match any type.
- The reason should be a brief one-sentence explanation of why you chose this type.`;

export type DocExtract = {
  doc_key: string;
  filename: string;
  summary: string;          // one-paragraph overview, 1-3 sentences
  key_facts: string[];      // up to 10 short factual bullets
  dates: string[];          // ISO YYYY-MM-DD strings or "YYYY" if no day; with context e.g. "2031 — MJOP valid through"
  amounts: string[];        // plain euro integers with label e.g. "12500 — reserve fund balance"
  parties: string[];        // VvE name, owner name, notary etc.
  flags: string[];          // up to 5 risk signals
  unreadable?: boolean;     // true if doc was empty / unreadable
};

function systemPrompt(docKey: string): string {
  const desc = DOC_DESCRIPTIONS[docKey]?.en ?? "an apartment-sale document";
  return `You read ONE document from a Dutch apartment-sale dossier and extract structured facts.

The document is: ${docKey} — ${desc}

Output JSON only, no prose, no code fences. Schema:

{
  "summary":    string,     // one paragraph (1-3 sentences, English) describing what this document is and its most material content.
  "key_facts":  string[],   // up to 10 short factual bullets in English, each citing the document. Numbers in euros: plain integers, no separator, no symbol.
  "dates":      string[],   // each entry: "<ISO date or year> — <what it refers to>". e.g. "2031 — MJOP valid through".
  "amounts":    string[],   // each entry: "<integer> — <label>". e.g. "12500 — reserve fund balance 2024".
  "parties":    string[],   // names of VvE, owners, notary, contractors, insurers etc.
  "flags":      string[],   // up to 5 risk signals an agent should know (e.g. "MJOP not updated since 2018", "reserve fund below MJOP recommendation").
  "unreadable": boolean     // true ONLY if the document is empty / blank / unreadable.
}

Rules:
- Cite only facts that are directly in this single document. Don't speculate.
- Keep it tight: a senior agent will skim this in 10 seconds.
- Empty arrays are fine if nothing relevant is present.
- Output JSON only.`;
}

function kopieIdPrompt(): string {
  return `You are verifying a KopieID-masked Dutch identity document for an apartment sale.

Check the following and report in JSON:
1. "bsn_masked": boolean — Is the BSN field blacked out / unreadable?
2. "photo_masked": boolean — Is the photo area masked?
3. "purpose_present": boolean — Does the document contain a "Doel" field with both "verkoop" and "apartmenthub" (case-insensitive)?
4. "looks_kopieid": boolean — Does the document appear to be generated by the KopieID app (watermark, format)?
5. "summary": string — One-sentence assessment.
6. "needs_review": boolean — true if any of checks 1-3 fail (bsn NOT masked, photo NOT masked, or purpose NOT present).
7. "flags": string[] — empty or up to 3 issues found.
8. "key_facts": string[] — empty or brief notes.
9. "dates": string[] — empty.
10. "amounts": string[] — empty.
11. "parties": string[] — empty.
12. "unreadable": boolean — true ONLY if the document is empty / blank / unreadable.

Output JSON only, no prose, no code fences.`;
}

function buildContent(opts: {
  bytes: Buffer;
  mime: string;
  filename: string;
}): Anthropic.MessageParam["content"] {
  const b64 = opts.bytes.toString("base64");
  if (opts.mime === "application/pdf") {
    return [
      {
        type: "document",
        source: { type: "base64", media_type: "application/pdf", data: b64 },
        title: opts.filename,
      } as Anthropic.ContentBlockParam,
      { type: "text", text: "Extract facts from this document per the schema." },
    ];
  }
  if (opts.mime.startsWith("image/")) {
    return [
      {
        type: "image",
        source: {
          type: "base64",
          media_type: opts.mime as "image/jpeg" | "image/png" | "image/webp" | "image/gif",
          data: b64,
        },
      },
      { type: "text", text: "Extract facts from this image per the schema." },
    ];
  }
  // Caller should have filtered these out, but guard just in case.
  return [{ type: "text", text: `Unsupported mime ${opts.mime}; return empty arrays and set unreadable=true.` }];
}

function safeParse(raw: string, docKey?: string): DocExtract | null {
  try {
    const cleaned = raw.trim().replace(/^```(?:json)?\s*|\s*```$/g, "");
    const obj = JSON.parse(cleaned) as Record<string, unknown>;
    const arr = (k: string, max: number) =>
      Array.isArray(obj[k])
        ? (obj[k] as unknown[])
            .filter((x) => typeof x === "string" && x.length > 0)
            .slice(0, max) as string[]
        : [];
    const base: DocExtract = {
      doc_key: "",
      filename: "",
      summary: typeof obj.summary === "string" ? String(obj.summary).slice(0, 600) : "",
      key_facts: arr("key_facts", 10),
      dates: arr("dates", 12),
      amounts: arr("amounts", 12),
      parties: arr("parties", 10),
      flags: arr("flags", 5),
      unreadable: obj.unreadable === true,
    };
    if (docKey === "seller_id_masked") {
      return {
        ...base,
        bsn_masked: obj.bsn_masked === true,
        photo_masked: obj.photo_masked === true,
        purpose_present: obj.purpose_present === true,
        looks_kopieid: obj.looks_kopieid === true,
        needs_review: obj.needs_review === true,
      } as DocExtract & { bsn_masked: boolean; photo_masked: boolean; purpose_present: boolean; looks_kopieid: boolean; needs_review: boolean };
    }
    return base;
  } catch {
    return null;
  }
}

export async function classifyDocument(opts: {
  bytes: Buffer;
  mime: string;
  filename: string;
}): Promise<ClassificationResult> {
  const anthropicKey =
    process.env.VERKOOP_ANTHROPIC_API_KEY ?? process.env.ANTHROPIC_API_KEY;
  if (!anthropicKey) {
    return { doc_key: "passport", confidence: "low", reason: "No API key configured — defaulting to passport" };
  }

  const client = new Anthropic({ apiKey: anthropicKey });
  try {
    const msg = await client.messages.create({
      model: MODEL,
      max_tokens: 200,
      system: CLASSIFICATION_PROMPT,
      messages: [
        {
          role: "user",
          content: buildContent(opts),
        },
      ],
    });
    const tb = msg.content.find(
      (b): b is Extract<typeof b, { type: "text" }> => b.type === "text"
    );
    if (!tb) throw new Error("no_text_response");
    const raw = tb.text.trim().replace(/^```(?:json)?\s*|\s*```$/g, "");
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const docKey =
      typeof parsed.doc_key === "string" && DOC_KEYS.includes(parsed.doc_key)
        ? parsed.doc_key
        : "passport";
    const confidence =
      parsed.confidence === "high" || parsed.confidence === "medium"
        ? parsed.confidence
        : "low";
    const reason =
      typeof parsed.reason === "string" ? parsed.reason : "";
    return { doc_key: docKey, confidence, reason };
  } catch (err) {
    console.error("[classifyDocument] failed:", err instanceof Error ? err.message : String(err));
    return { doc_key: "passport", confidence: "low", reason: "Classification failed — defaulting to passport" };
  }
}

// Run the extraction for one verkoop_files row. Updates the row in place with
// ai_extract / ai_extract_status / ai_extract_at / ai_extract_error.
// Returns the persisted extract, or null on failure (status is recorded).
export async function extractSingleDocument(file: {
  id: string;
  doc_key: string;
  filename: string;
  mime_type: string | null;
  blob_url: string;
}): Promise<DocExtract | null> {
  const sb = supabaseAdmin();
  const mime = file.mime_type || "application/octet-stream";

  // Skip formats Claude can't natively read.
  if (mime !== "application/pdf" && !mime.startsWith("image/")) {
    await sb
      .from("verkoop_files")
      .update({
        ai_extract: null,
        ai_extract_status: "skipped",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: `Unsupported mime type: ${mime}`,
      })
      .eq("id", file.id);
    return null;
  }

  const anthropicKey =
    process.env.VERKOOP_ANTHROPIC_API_KEY ?? process.env.ANTHROPIC_API_KEY;
  if (!anthropicKey) {
    await sb
      .from("verkoop_files")
      .update({
        ai_extract_status: "failed",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: "ANTHROPIC_API_KEY missing",
      })
      .eq("id", file.id);
    return null;
  }

  // Mark in-flight so a parallel call won't double-process.
  await sb
    .from("verkoop_files")
    .update({ ai_extract_status: "pending", ai_extract_error: null })
    .eq("id", file.id);

  let bytes: ArrayBuffer | null = null;
  try {
    if (/^https?:\/\//i.test(file.blob_url)) {
      const res = await fetch(file.blob_url);
      if (res.ok) bytes = await res.arrayBuffer();
    } else {
      bytes = await downloadFile(file.blob_url);
    }
  } catch (err) {
    await sb
      .from("verkoop_files")
      .update({
        ai_extract_status: "failed",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: `download_failed: ${err instanceof Error ? err.message : String(err)}`,
      })
      .eq("id", file.id);
    return null;
  }
  if (!bytes) {
    await sb
      .from("verkoop_files")
      .update({
        ai_extract_status: "failed",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: "download_returned_empty",
      })
      .eq("id", file.id);
    return null;
  }

  const client = new Anthropic({ apiKey: anthropicKey });
  let raw: string;
  try {
    const msg = await client.messages.create({
      model: MODEL,
      max_tokens: 900,
      system: file.doc_key === "seller_id_masked" ? kopieIdPrompt() : systemPrompt(file.doc_key),
      messages: [
        {
          role: "user",
          content: buildContent({
            bytes: Buffer.from(bytes),
            mime,
            filename: file.filename,
          }),
        },
      ],
    });
    const tb = msg.content.find(
      (b): b is Extract<typeof b, { type: "text" }> => b.type === "text"
    );
    if (!tb) throw new Error("no_text_response");
    raw = tb.text;
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    await sb
      .from("verkoop_files")
      .update({
        ai_extract_status: "failed",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: `claude: ${detail}`.slice(0, 800),
      })
      .eq("id", file.id);
    return null;
  }

  const parsed = safeParse(raw, file.doc_key);
  if (!parsed) {
    await sb
      .from("verkoop_files")
      .update({
        ai_extract_status: "failed",
        ai_extract_at: new Date().toISOString(),
        ai_extract_error: `parse_failed: ${raw.slice(0, 300)}`,
      })
      .eq("id", file.id);
    return null;
  }
  parsed.doc_key = file.doc_key;
  parsed.filename = file.filename;

  await sb
    .from("verkoop_files")
    .update({
      ai_extract: parsed,
      ai_extract_status: "done",
      ai_extract_at: new Date().toISOString(),
      ai_extract_error: null,
    })
    .eq("id", file.id);

  return parsed;
}

// Pretty-print a stored extract as a text block for the synthesis prompt.
export function formatExtractForSynthesis(e: DocExtract): string {
  const lines: string[] = [];
  lines.push(`## ${e.doc_key} — ${e.filename}`);
  if (e.unreadable) {
    lines.push("_(document was unreadable / empty)_");
    return lines.join("\n");
  }
  if (e.summary) lines.push(`Summary: ${e.summary}`);
  if (e.key_facts.length) {
    lines.push("Key facts:");
    for (const f of e.key_facts) lines.push(`- ${f}`);
  }
  if (e.dates.length) {
    lines.push("Dates:");
    for (const d of e.dates) lines.push(`- ${d}`);
  }
  if (e.amounts.length) {
    lines.push("Amounts (EUR):");
    for (const a of e.amounts) lines.push(`- ${a}`);
  }
  if (e.parties.length) {
    lines.push("Parties:");
    for (const p of e.parties) lines.push(`- ${p}`);
  }
  if (e.flags.length) {
    lines.push("Flags:");
    for (const fl of e.flags) lines.push(`- ${fl}`);
  }
  return lines.join("\n");
}
