export const RADIO_VALUES: Record<string, { nl: string; en: string }> = {
  blijft:   { nl: "Blijft achter", en: "Stays behind" },
  mee:      { nl: "Gaat mee", en: "Goes with seller" },
  overname: { nl: "Ter overname", en: "For takeover" },
  nvt:      { nl: "N.v.t.", en: "N/A" },
};

export type InventoryItem = {
  key: string;
  label_nl: string;
  label_en: string;
  category_nl: string;
  category_en: string;
};

export const CATEGORIES: { nl: string; en: string }[] = [
  { nl: "Woning \u00b7 interieur", en: "Home \u00b7 interior" },
  { nl: "Keuken", en: "Kitchen" },
  { nl: "Sanitair en badkamer", en: "Sanitary and bathroom" },
  { nl: "Verwarming, ventilatie en energie", en: "Heating, ventilation and energy" },
  { nl: "Woning \u00b7 exterieur", en: "Home \u00b7 exterior" },
  { nl: "Tuin en berging", en: "Garden and storage" },
  { nl: "Overige zaken", en: "Other items" },
];

export const INVENTORY_ITEMS: InventoryItem[] = [
  { key: "item_1", label_nl: "Deurbel", label_en: "Doorbell", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_2", label_nl: "Videofoon / intercom", label_en: "Video phone / intercom", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_3", label_nl: "Rookmelders / brandmelders", label_en: "Smoke detectors / fire alarms", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_4", label_nl: "(Klok)thermostaat", label_en: "(Clock) thermostat", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_5", label_nl: "Alarminstallatie", label_en: "Alarm system", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_6", label_nl: "Gordijnrails", label_en: "Curtain rails", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_7", label_nl: "Gordijnen", label_en: "Curtains", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_8", label_nl: "Rolgordijnen", label_en: "Roller blinds", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_9", label_nl: "Vitrages", label_en: "Sheer curtains", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_10", label_nl: "Jaloezieen / lamellen", label_en: "Blinds / slats", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_11", label_nl: "Rolluiken", label_en: "Shutters", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_12", label_nl: "Zonwering binnen", label_en: "Indoor sun shading", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_13", label_nl: "Vloerbedekking / vinyl", label_en: "Flooring / vinyl", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_14", label_nl: "Parket / laminaat", label_en: "Parquet / laminate", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_15", label_nl: "Losliggende (vloer)delen", label_en: "Loose floor parts", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_16", label_nl: "Wandtegels / lambrisering", label_en: "Wall tiles / paneling", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_17", label_nl: "Trapbekleding", label_en: "Stair covering", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_18", label_nl: "Voorzetramen / radiatorfolie", label_en: "Secondary glazing / radiator foil", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_19", label_nl: "(Inbouw)spiegels", label_en: "Built-in mirrors", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_20", label_nl: "Schilderij-ophangsysteem", label_en: "Picture hanging system", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_21", label_nl: "Losse en inbouwkasten", label_en: "Freestanding and built-in closets", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_22", label_nl: "Traphekje", label_en: "Stair gate", category_nl: "Woning \u00b7 interieur", category_en: "Home \u00b7 interior" },
  { key: "item_23", label_nl: "Keukenblok met bovenkasten", label_en: "Kitchen unit with wall cabinets", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_24", label_nl: "Werkblad", label_en: "Worktop", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_25", label_nl: "Spoelbak / kraan", label_en: "Sink / tap", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_26", label_nl: "Afzuigkap", label_en: "Extractor hood", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_27", label_nl: "Kookplaat (gas / inductie / keramisch)", label_en: "Hob (gas / induction / ceramic)", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_28", label_nl: "Fornuis", label_en: "Stove", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_29", label_nl: "Oven", label_en: "Oven", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_30", label_nl: "Combi-oven / stoomoven", label_en: "Combi-oven / steam oven", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_31", label_nl: "Magnetron", label_en: "Microwave", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_32", label_nl: "Koelkast", label_en: "Refrigerator", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_33", label_nl: "Vriezer", label_en: "Freezer", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_34", label_nl: "Koel-vriescombinatie", label_en: "Fridge-freezer combo", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_35", label_nl: "Vaatwasser", label_en: "Dishwasher", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_36", label_nl: "Kokendwaterkraan (Quooker)", label_en: "Boiling water tap (Quooker)", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_37", label_nl: "Koffiezetsysteem (inbouw)", label_en: "Built-in coffee machine", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_38", label_nl: "Wijnkoeler", label_en: "Wine cooler", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_39", label_nl: "Warmhoudlade", label_en: "Warming drawer", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_40", label_nl: "Afvalscheiding (inbouw)", label_en: "Built-in waste separation", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_41", label_nl: "Keukenverlichting", label_en: "Kitchen lighting", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_42", label_nl: "Keukenaccessoires", label_en: "Kitchen accessories", category_nl: "Keuken", category_en: "Kitchen" },
  { key: "item_43", label_nl: "Wastafel(s)", label_en: "Washbasin(s)", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_44", label_nl: "Wastafelmeubel", label_en: "Washbasin cabinet", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_45", label_nl: "Spiegel(s)", label_en: "Mirror(s)", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_46", label_nl: "Douche(deur) / douchescherm", label_en: "Shower door / screen", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_47", label_nl: "Douchegarnituur", label_en: "Shower fixture", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_48", label_nl: "Bad", label_en: "Bathtub", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_49", label_nl: "2e toilet / fontein", label_en: "2nd toilet / bidet", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_50", label_nl: "Toiletkast / planchet", label_en: "Toilet cabinet / shelf", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_51", label_nl: "Handdoekradiator", label_en: "Towel radiator", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_52", label_nl: "Ventilator badkamer", label_en: "Bathroom fan", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_53", label_nl: "Closetrolhouder / handdoekhaken", label_en: "Toilet roll holder / towel hooks", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_54", label_nl: "Badkameraccessoires", label_en: "Bathroom accessories", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_55", label_nl: "Toiletaccessoires", label_en: "Toilet accessories", category_nl: "Sanitair en badkamer", category_en: "Sanitary and bathroom" },
  { key: "item_56", label_nl: "CV-ketel met toebehoren", label_en: "Boiler with accessories", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_57", label_nl: "Radiatoren / convectoren", label_en: "Radiators / convectors", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_58", label_nl: "Radiatorknoppen / thermostaatkranen", label_en: "Radiator valves / thermostatic taps", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_59", label_nl: "Vloerverwarming", label_en: "Underfloor heating", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_60", label_nl: "Vloerverwarmingsverdeler", label_en: "Underfloor heating manifold", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_61", label_nl: "(Mechanische) ventilatie / WTW", label_en: "(Mechanical) ventilation / HRV", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_62", label_nl: "Airconditioning", label_en: "Air conditioning", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_63", label_nl: "(Warmwater)boiler / geiser", label_en: "(Hot water) boiler / geyser", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_64", label_nl: "Waterontharder", label_en: "Water softener", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_65", label_nl: "Zonnepanelen", label_en: "Solar panels", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_66", label_nl: "Zonneboiler", label_en: "Solar boiler", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_67", label_nl: "Warmtepomp", label_en: "Heat pump", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_68", label_nl: "Thuisbatterij", label_en: "Home battery", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_69", label_nl: "Laadpunt elektrische auto", label_en: "EV charging point", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_70", label_nl: "Open haard / houtkachel / allesbrander", label_en: "Open fireplace / wood stove / multi-burner", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_71", label_nl: "Rookgasafvoer / schoorsteen", label_en: "Flue / chimney", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_72", label_nl: "Isolatievoorzieningen", label_en: "Insulation", category_nl: "Verwarming, ventilatie en energie", category_en: "Heating, ventilation and energy" },
  { key: "item_73", label_nl: "Buitenverlichting", label_en: "Outdoor lighting", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_74", label_nl: "Tijd- / schemerschakelaar / bewegingsmelder", label_en: "Timer / twilight switch / motion sensor", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_75", label_nl: "Huisnummer / naambordje", label_en: "House number / name plate", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_76", label_nl: "Brievenbus", label_en: "Mailbox", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_77", label_nl: "(Veiligheids)sloten en inbraakpreventie", label_en: "Security locks and burglary prevention", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_78", label_nl: "Camerabewaking / deurbelcamera", label_en: "Camera surveillance / doorbell camera", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_79", label_nl: "Screens / rolluiken buiten", label_en: "Screens / exterior shutters", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_80", label_nl: "Zonwering buiten", label_en: "Exterior sun shading", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_81", label_nl: "Luifel / markies", label_en: "Awning / canopy", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_82", label_nl: "Schotel / antenne", label_en: "Satellite dish / antenna", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_83", label_nl: "Vlaggenmast(houder)", label_en: "Flagpole (holder)", category_nl: "Woning \u00b7 exterieur", category_en: "Home \u00b7 exterior" },
  { key: "item_84", label_nl: "Tuinaanleg / beplanting", label_en: "Garden layout / planting", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_85", label_nl: "Tuinverlichting", label_en: "Garden lighting", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_86", label_nl: "Buitenkraan", label_en: "Outdoor tap", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_87", label_nl: "Beregeningsinstallatie", label_en: "Irrigation system", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_88", label_nl: "Tuinhuis / blokhut / schuur", label_en: "Garden shed / cabin", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_89", label_nl: "Inventaris tuinhuis / schuur", label_en: "Contents of garden shed", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_90", label_nl: "Vijver (met pomp)", label_en: "Pond (with pump)", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_91", label_nl: "Broeikas", label_en: "Greenhouse", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_92", label_nl: "Pergola / overkapping", label_en: "Pergola / canopy", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_93", label_nl: "(Sier)hekwerk / schutting", label_en: "Ornamental fence / fencing", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_94", label_nl: "Tuinmeubilair (los)", label_en: "Garden furniture (loose)", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_95", label_nl: "Barbecue (inbouw)", label_en: "Barbecue (built-in)", category_nl: "Tuin en berging", category_en: "Garden and storage" },
  { key: "item_96", label_nl: "Wasmachine", label_en: "Washing machine", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_97", label_nl: "Wasdroger", label_en: "Dryer", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_98", label_nl: "(Elektrische) garagedeur + afstandsbediening", label_en: "(Electric) garage door + remote", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_99", label_nl: "Garagestelling", label_en: "Garage shelving", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_100", label_nl: "Vlizotrap / zoldertrap", label_en: "Attic ladder / loft ladder", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_101", label_nl: "Dakraam(rolgordijn)", label_en: "Roof window (roller blind)", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_102", label_nl: "(Ingebouwde) kluis", label_en: "Built-in safe", category_nl: "Overige zaken", category_en: "Other items" },
  { key: "item_103", label_nl: "Brandblusser", label_en: "Fire extinguisher", category_nl: "Overige zaken", category_en: "Other items" },
];

export const ITEM_MAP: Record<string, InventoryItem> = Object.fromEntries(
  INVENTORY_ITEMS.map((i) => [i.key, i])
);